insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Konstanze Shrieve', 'Debra', '2022-08-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Florenza Newey', 'Daystar', '2022-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Creigh Bernardotte', 'East', '2022-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Perle Pennycook', 'Sage', '2022-12-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shaina Adamkiewicz', 'Straubel', '2023-05-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlow Cattow', 'Barnett', '2022-08-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arman Peskin', 'Mayer', '2023-07-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Evin Torra', 'Lighthouse Bay', '2023-03-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Janey Grasha', 'Montana', '2022-10-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Keenan Anstey', 'Dovetail', '2023-01-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gaynor Korejs', 'Bunker Hill', '2022-10-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aviva Treker', 'Continental', '2022-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rubi Jansen', 'Twin Pines', '2022-09-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adelbert Madders', 'Darwin', '2023-04-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tucker Andino', 'Northview', '2023-07-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Heinrik Saunders', 'Lunder', '2022-09-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Concettina Alldred', 'Di Loreto', '2023-05-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Israel Koschke', 'Heffernan', '2022-11-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maris Ivashev', 'Village Green', '2023-03-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bradney Troctor', 'Hovde', '2022-10-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Prue Gogan', 'Burrows', '2023-03-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chariot Refford', 'Superior', '2022-12-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mada Wrey', 'East', '2023-07-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Angie Wollard', 'Division', '2023-01-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bennett Jeavons', 'Sage', '2023-04-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Paco Levison', 'Miller', '2023-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tammy Tozer', 'Paget', '2023-02-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Quintus Bailess', 'Parkside', '2022-10-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Devan Minmagh', 'Elmside', '2022-10-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dalenna Borrie', 'Mcbride', '2022-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eugenio Hennemann', 'Anderson', '2023-03-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lloyd Ardley', 'Northwestern', '2023-02-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Donavon Mandry', 'Lerdahl', '2022-08-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlyn Gammade', 'Evergreen', '2023-03-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Melisenda Wyldish', 'Shopko', '2022-12-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giustino Le Grice', 'Dapin', '2023-06-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mordecai Kohnemann', 'Caliangt', '2023-02-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Camellia Klein', 'Tomscot', '2022-12-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ase Bowery', 'Harper', '2022-10-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pauline Gibben', 'Mccormick', '2022-12-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arden Marks', 'Morning', '2023-03-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eimile Joynson', 'Arizona', '2023-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garland Sneden', 'Pond', '2023-02-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leandra Guyers', 'Mendota', '2022-09-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Helga Tutchell', 'Nancy', '2022-12-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Florence Furtado', 'Aberg', '2023-02-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gannon Jennick', 'Bowman', '2022-10-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hersh Kinglake', 'Lawn', '2023-03-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Papagena Dunnan', 'Vera', '2023-05-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Klarrisa Keely', 'Arizona', '2023-02-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aviva Gruczka', 'Homewood', '2022-12-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dennet Locard', 'Weeping Birch', '2023-01-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Charlotte Bulled', 'Walton', '2022-09-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jo-ann Gonnin', 'Porter', '2023-01-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rozamond Vouls', 'Lakeland', '2022-09-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Langsdon Reddle', 'Larry', '2023-04-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nancie Sloegrave', 'Canary', '2023-02-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Katie Yukhin', 'Hermina', '2023-03-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Candi Wrighton', 'Harper', '2022-07-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aurelea Canti', 'Morrow', '2023-06-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Orton Buswell', 'Heffernan', '2022-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lorine Scolding', 'Farwell', '2022-10-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Davine Lafoy', 'Morningstar', '2022-07-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cora Barley', 'Brentwood', '2022-09-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Duane Adam', 'Monument', '2022-08-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arne Friedman', 'Karstens', '2023-05-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tierney Sargent', 'Morrow', '2023-07-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pren Parlot', 'Nevada', '2023-05-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Krista Ioannidis', 'Di Loreto', '2023-05-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rodie Biaggetti', 'Union', '2022-07-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hamlen Heeron', 'Sugar', '2022-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Moll Ringham', 'Killdeer', '2023-03-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gottfried Kapiloff', 'Eagle Crest', '2022-12-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Laure Lapthorne', 'Utah', '2023-02-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tybie Podd', 'Anzinger', '2022-10-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Zara Allbrook', 'Gateway', '2023-02-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Olivier Hearne', 'Mallory', '2023-03-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pacorro Blyde', 'Saint Paul', '2022-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dolly Jelks', 'Kipling', '2022-08-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Toby Bewsy', 'Spohn', '2022-11-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cammy Powner', 'Emmet', '2022-10-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Violetta Lince', 'Mccormick', '2023-02-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Berte Vockins', 'Larry', '2022-10-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adoree Eltune', 'Maple Wood', '2022-07-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jocelin Rattenbury', 'Elmside', '2022-12-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sansone Matthiesen', 'Hintze', '2023-06-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Guthry Syers', 'Towne', '2022-10-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Weider Hodgen', 'Iowa', '2022-09-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Justin Hebner', 'Mesta', '2023-02-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jerry Imorts', 'Marcy', '2022-10-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Waverley Balog', 'Dapin', '2022-09-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dredi Jeskins', 'Lillian', '2023-02-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dru Elis', 'Goodland', '2022-10-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garvy Alcorn', 'Bluestem', '2022-08-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nathalia Basset', 'Northland', '2023-04-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hussein Danaher', 'Cherokee', '2023-02-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Samuel Buddle', 'Macpherson', '2022-09-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gwenneth Haquin', 'Sage', '2023-06-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Riobard Harwick', 'Shopko', '2023-02-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Johnette Klesl', 'Quincy', '2023-07-22');
