insert into tren (modelo, capacidad) values ('612 Scaglietti', 1);
insert into tren (modelo, capacidad) values ('Sierra 1500', 2);
insert into tren (modelo, capacidad) values ('Impreza', 3);
insert into tren (modelo, capacidad) values ('Grand Vitara', 4);
insert into tren (modelo, capacidad) values ('Camry Hybrid', 5);
insert into tren (modelo, capacidad) values ('Lancer Evolution', 6);
insert into tren (modelo, capacidad) values ('Explorer Sport', 7);
insert into tren (modelo, capacidad) values ('DeVille', 8);
insert into tren (modelo, capacidad) values ('Coupe GT', 9);
insert into tren (modelo, capacidad) values ('9-5', 10);
insert into tren (modelo, capacidad) values ('Ion', 11);
insert into tren (modelo, capacidad) values ('E350', 12);
insert into tren (modelo, capacidad) values ('Town Car', 13);
insert into tren (modelo, capacidad) values ('TSX', 14);
insert into tren (modelo, capacidad) values ('Blazer', 15);
insert into tren (modelo, capacidad) values ('X-90', 16);
insert into tren (modelo, capacidad) values ('2500', 17);
insert into tren (modelo, capacidad) values ('Accent', 18);
insert into tren (modelo, capacidad) values ('Concorde', 19);
insert into tren (modelo, capacidad) values ('QX', 20);
insert into tren (modelo, capacidad) values ('tC', 21);
insert into tren (modelo, capacidad) values ('Elantra', 22);
insert into tren (modelo, capacidad) values ('370Z', 23);
insert into tren (modelo, capacidad) values ('2500', 24);
insert into tren (modelo, capacidad) values ('Vanagon', 25);
insert into tren (modelo, capacidad) values ('Focus', 26);
insert into tren (modelo, capacidad) values ('Santa Fe', 27);
insert into tren (modelo, capacidad) values ('Wrangler', 28);
insert into tren (modelo, capacidad) values ('S-Class', 29);
insert into tren (modelo, capacidad) values ('Camaro', 30);
insert into tren (modelo, capacidad) values ('Express 3500', 31);
insert into tren (modelo, capacidad) values ('FX', 32);
insert into tren (modelo, capacidad) values ('Corvette', 33);
insert into tren (modelo, capacidad) values ('1500', 34);
insert into tren (modelo, capacidad) values ('Fusion', 35);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 36);
insert into tren (modelo, capacidad) values ('Suburban 2500', 37);
insert into tren (modelo, capacidad) values ('TSX', 38);
insert into tren (modelo, capacidad) values ('SLS AMG', 39);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 40);
insert into tren (modelo, capacidad) values ('Sonoma Club Coupe', 41);
insert into tren (modelo, capacidad) values ('3 Series', 42);
insert into tren (modelo, capacidad) values ('GTO', 43);
insert into tren (modelo, capacidad) values ('4000CS Quattro', 44);
insert into tren (modelo, capacidad) values ('Z4', 45);
insert into tren (modelo, capacidad) values ('B-Series Plus', 46);
insert into tren (modelo, capacidad) values ('XK Series', 47);
insert into tren (modelo, capacidad) values ('Phantom', 48);
insert into tren (modelo, capacidad) values ('Boxster', 49);
insert into tren (modelo, capacidad) values ('GX', 50);
insert into tren (modelo, capacidad) values ('Civic', 51);
insert into tren (modelo, capacidad) values ('4Runner', 52);
insert into tren (modelo, capacidad) values ('CLK-Class', 53);
insert into tren (modelo, capacidad) values ('Laser', 54);
insert into tren (modelo, capacidad) values ('Malibu', 55);
insert into tren (modelo, capacidad) values ('Cabriolet', 56);
insert into tren (modelo, capacidad) values ('S-Class', 57);
insert into tren (modelo, capacidad) values ('M', 58);
insert into tren (modelo, capacidad) values ('Imperial', 59);
insert into tren (modelo, capacidad) values ('S4', 60);
insert into tren (modelo, capacidad) values ('Frontier', 61);
insert into tren (modelo, capacidad) values ('Endeavor', 62);
insert into tren (modelo, capacidad) values ('Town & Country', 63);
insert into tren (modelo, capacidad) values ('New Beetle', 64);
insert into tren (modelo, capacidad) values ('Jetta', 65);
insert into tren (modelo, capacidad) values ('Silverado', 66);
insert into tren (modelo, capacidad) values ('E250', 67);
insert into tren (modelo, capacidad) values ('X6 M', 68);
insert into tren (modelo, capacidad) values ('Mazda5', 69);
insert into tren (modelo, capacidad) values ('240SX', 70);
insert into tren (modelo, capacidad) values ('LeMans', 71);
insert into tren (modelo, capacidad) values ('Expedition', 72);
insert into tren (modelo, capacidad) values ('CX-9', 73);
insert into tren (modelo, capacidad) values ('Civic Si', 74);
insert into tren (modelo, capacidad) values ('Yukon', 75);
insert into tren (modelo, capacidad) values ('Z3', 76);
insert into tren (modelo, capacidad) values ('ES', 77);
insert into tren (modelo, capacidad) values ('LR4', 78);
insert into tren (modelo, capacidad) values ('Ciera', 79);
insert into tren (modelo, capacidad) values ('Quattroporte', 80);
insert into tren (modelo, capacidad) values ('Altima', 81);
insert into tren (modelo, capacidad) values ('CLS-Class', 82);
insert into tren (modelo, capacidad) values ('E-350 Super Duty Van', 83);
insert into tren (modelo, capacidad) values ('Transit Connect', 84);
insert into tren (modelo, capacidad) values ('300CE', 85);
insert into tren (modelo, capacidad) values ('Yukon', 86);
insert into tren (modelo, capacidad) values ('Commander', 87);
insert into tren (modelo, capacidad) values ('2500 Club Coupe', 88);
insert into tren (modelo, capacidad) values ('LeMans', 89);
insert into tren (modelo, capacidad) values ('Econoline E250', 90);
insert into tren (modelo, capacidad) values ('Riviera', 91);
insert into tren (modelo, capacidad) values ('Sedona', 92);
insert into tren (modelo, capacidad) values ('Villager', 93);
insert into tren (modelo, capacidad) values ('J', 94);
insert into tren (modelo, capacidad) values ('RX Hybrid', 95);
insert into tren (modelo, capacidad) values ('C30', 96);
insert into tren (modelo, capacidad) values ('Coupe GT', 97);
insert into tren (modelo, capacidad) values ('Jimmy', 98);
insert into tren (modelo, capacidad) values ('Ram Wagon B350', 99);
insert into tren (modelo, capacidad) values ('Sentra', 100);
